### ISSUE TITLE
Download mp4 not working

### ISSUE THREAD

**Issue by vh133** [neuro-sys/tumblr-likes-downloader#35]
First of all: Thank you for fixing the authorization flow. The logon and the image download working great!
But on my testsystems (Win and Linux), downloads of mp4-file are not working. The downloaded mp4-files have all the same size (145kb) and contain html-content (see attachment). 
Is this a problem in general?
![2018-09-24 12_19_20-window](https://user-images.githubusercontent.com/40110603/45947501-c900d300-bff4-11e8-8526-d2823c286988.png)

**Comment by blistex** [comment]
Yes videos won't download on mac either. Thank you for looking into it.

**Comment by neuro-sys** [comment]
Fix is here: https://github.com/neuro-sys/tumblr-likes-downloader/pull/53
