### ISSUE TITLE
Downloading isn't working

### ISSUE THREAD

**Issue by kerreej** [neuro-sys/tumblr-likes-downloader#36]
Any help with this is appreciated. 

I am using Mac OS Mojave, Safari Version 12.0 (14606.1.36.1.9) on 
I received the following message: 

* Starting...
Initializing environment...
done
Authorizing on tumblr...
Waiting until authorization flow is completed
Authorization URL: https://www.tumblr.com/oauth/authorize?oauth_token=4WxEfWVt9WOx16v5PfzrfghI05oZZO6Zcl3lFY4U7rfSyo0vaj
Please check your browser, and log into Tumblr as usual, then come back to this application
VLezV1k6ojj0ulYOOnrQYH2Z77let6OHsPzRcS1OYsUtm14QOq 4WxEfWVt9WOx16v5PfzrfghI05oZZO6Zcl3lFY4U7rfSyo0vaj
Releasing now
Auth completed
Ask for liked posts 1 - 20...
done
Downloading https://raymondmartinez1.tumblr.com/video_file/t:UwAcewHtfmaPGHEDRx8lGg/179228783980/tumblr_p4y6ocgr8Y1wn1gwl
There was an error:
open /private/var/folders/tl/w09w1rc94mnbp9pk1jp65gbw0000gn/T/AppTranslocation/3EC65D06-0ACE-4A8C-A730-BB37A494F48B/d/tumblr-downloader-gui.app/Contents/MacOS/ikerry.tumblr.com/raymondmartinez1/tumblr_p4y6ocgr8Y1wn1gwl.mp4: no such file or directory
* Finished...

Kerry

**Comment by neuro-sys** [comment]
@kerreej Hi, could you try setting "Target Location" to your Desktop, or Home directory?

**Comment by ycarbon** [comment]
I have the same problem, I appreciate any help with this issue
I have tried differents paths and none works...
Thank you!

macOS High Sierra 10.13.1
Chrome 70.0.3538.110 (Build oficial) (64 bits)


Authorizing on tumblr...
Waiting until authorization flow is completed
Authorization URL: https://www.tumblr.com/oauth/authorize?oauth_token=IhpQQPiFNxt36V8EN9zZYWCKLWXzuP60C9l5X5mpaOZZst2ejJ
Please check your browser, and log into Tumblr as usual, then come back to this application
4PMfbLwfkzebvpo10zZA8MfJpPAZRhlGvwucpZpueAB4CLd3iX IhpQQPiFNxt36V8EN9zZYWCKLWXzuP60C9l5X5mpaOZZst2ejJ
Releasing now
Auth completed
Ask for liked posts 1 - 20...
done
Downloading https://66.media.tumblr.com/e0cb1f98ea8ce2706e581edf02d8db74/tumblr_oosmm6fXWt1t00xvao1_500.jpg
There was an error:
open //myg7468.tumblr.com/suckmypixxxel/tumblr_oosmm6fXWt1t00xvao1_500.jpg: no such file or directory
* Finished...

**Comment by ycarbon** [comment]
Hello: FYI
I have solved this error using a folder without blank spaces in its name
Regards

**Comment by neuro-sys** [comment]
This is indeed an issue with setting a target folder that is not accessible.
