### ISSUE TITLE
Videolar indirilmior!

### ISSUE THREAD

**Issue by blistex** [neuro-sys/tumblr-likes-downloader#37]
Selam,

merak ettim, acaba bu muhtesem uygulamayi devam sürdürmeyi düsünüyormusunuz? Cok süper ve ise yarayan bir uygulama ve bunun olmamasi büyük bir kayip ve yazik olur. Simidiye kadar verdiyin emekler icin tesekkürler :)

**Comment by neuro-sys** [comment]
@blistex Selam, tesekkurler. Vakit buldukca goz atmaya calisiyorum.
