### ISSUE TITLE
stops after tumblr login

### ISSUE THREAD

**Issue by scribb498** [neuro-sys/tumblr-likes-downloader#38]
`* Starting...
Initializing environment... done
Authorizing on tumblr...
Waiting until authorization flow is completed
Authorization URL: https://www.tumblr.com/oauth/authorize?oauth_token=
Please check your browser, and log into Tumblr as usual, then come back to this application
Created new window in existing browser session.`
there is no pop up in my browser, admittedly in an attempt to make it it work i created a second application for it.
I'm using Chrome on Linux Ubuntu 16.04.5 LTS

**Comment by CaptainOgnog** [comment]
I, too,  have this issue. Previous issue threads said that the program didn't like number or special character in the name, and that isn't the issue. 
Also, making the target location the home directory or desktop doesn't solve the issue either. 
Another also, thank you for making this program, it's greatly appreciated.

**Comment by yanglifu90** [comment]
Me, too. I get an empty auth_token. Maybe it is because tumblr is blocked where I live and some parameters need to be changed? I used a VPN to visit tumblr.

**Comment by neuro-sys** [comment]
As this is a QT application, based on the documentation you could set an Environment Variable to use an http proxy thus:

> proxy settings from the "http_proxy" environment variable. This variable must be a URL using one of the following schemes: "http", "socks5" or "socks5h".
