### ISSUE TITLE
"Failed to parse"

### ISSUE THREAD

**Issue by RepublicJ** [neuro-sys/tumblr-likes-downloader#39]
Heya,

I've made my way through the program so far, and am stuck on this.

Ask for liked posts 1 - 20... There was an error:
Failed to parse: response.liked_posts

Does it matter that my like page is private / public? (i've tried both).

Could you help me?

**Comment by fourteeth** [comment]
Same error

**Comment by RepublicJ** [comment]
Thanks, that worked a treat! Just tagging on, did you manage to find a way to download the videos you liked? or is this limited to pics and gifs?

**Comment by osopolare** [comment]
The format of the blog name is key.  Make it "blogname.tumblr.com" (without the quotes of course).  I found that even "http://blogname.tumblr.com/" didn't work.

It does get videos.  Byebye tumblr.  Was nice knowing you.

**Comment by 5h4d0w-ph03n1x** [comment]
I'm getting the same error.
I checked to make sure that 'Blog Name' is correctly formatted (blogname.tumblr.com) and I'm still getting this error.

Please Help..

**Comment by 5h4d0w-ph03n1x** [comment]
I fixed it. The problem was that my blog name began with a number and I guess this program doesn't like that.

**Comment by neuro-sys** [comment]
> The problem was that my blog name began with a number and I guess this program doesn't like that.
That's very interesting. I'm not quite sure why that would cause a problem. Although with the release 0.0.3 I simplified (hopefully) the "Blog Name" input, by changing it to simply "User Name" to avoid any confusion.
