### ISSUE TITLE
Only can acess certain post

### ISSUE THREAD

**Issue by porschewe** [neuro-sys/tumblr-likes-downloader#41]
it does work quite well, but the thing right now I am facing to is

Ask for liked posts 104 - 123... done
Downloading https://66.media.tumblr.com/...jpg..........................(not actually shows like this, but just try to save some space for the questions)..................https://66.media.tumblr.com/...jpg
* Finished...

I liked more than 2000+ of posts and it only read up to 123, and it stooped.

Thanks.

**Comment by neuro-sys** [comment]
@porschewe Can you try this release? https://github.com/neuro-sys/tumblr-likes-downloader/releases/tag/0.0.2

**Comment by porschewe** [comment]
Thanks, I will try that! I appreciated !

**Comment by porschewe** [comment]
> @porschewe Can you try this release? https://github.com/neuro-sys/tumblr-likes-downloader/releases/tag/0.0.2

Hello, I tried, it still stop at ask for liked posts 123 - 142... done
File already exists, skipping
*Finished...

I tried older vision few days ago, first time it can goes up to 1000+somthing and then it stoped, because of that API limitation, do I need to scroll my 2000+ likes all the way to the bottom and use this app?
Thanks!

**Comment by neuro-sys** [comment]
You can now set the start offset if that helps: https://github.com/neuro-sys/tumblr-likes-downloader/pull/53
