### ISSUE TITLE
Can't get past "started"

### ISSUE THREAD

**Issue by baileyboybee** [neuro-sys/tumblr-likes-downloader#42]
Hi, running Windows 64-bit using Chrome. I followed instructions -- registered the app (double checked that I matched application website and callback URLs). Put in my keys (double-checked those as well). Did get an email from Tumblr saying that I had authorized my "app". I hit the button and it says "starting" but never goes beyond that. Just hangs. Any suggestions?

![downloader](https://user-images.githubusercontent.com/45740147/49701714-403a1200-fbb5-11e8-82fb-c2b00773da97.jpg)

**Comment by Dalton-West** [comment]
Remove any http:// protocols. It will work.

**Comment by baileyboybee** [comment]
I'm not using "http:// anywhere except in the registered app (http://localhost:8080/tumblr and http://localhost:8080/tumblr/callback). My blog name is name.tumblr.com. Straight copied the keys (no http) and I did change target location to c:/users/name/desktop. I hit download and "starting" shows up, but hours can go by and nothing happens. Does it take this long?

**Comment by Dalton-West** [comment]
I was able to back up my likes. By moving the directory to an external HDD.
"E:\Tumblr Backup" I didn't have any issues. Its fired up after I removed
http:// from http://name.tumblr.com. I would try running it again with a
different director. Maybe try C:/folderName

**Comment by neuro-sys** [comment]
Please try the release 0.0.3, and re-open if the problem persists.
