### ISSUE TITLE
Specify liked post Offset when running again.

### ISSUE THREAD

**Issue by BlisteringSyko** [neuro-sys/tumblr-likes-downloader#44]
So i have 32,025 likes currently in my blog. Can you add a field to specify the offset to start at, if this isnt already accounted for some how automatically.   

My hope is to hit the limit, note down the last range it stopped at, make a new api key and then start where it left off. and repeat.. It keeps stopping at 1029 - 1048.

The issue im seeing is if i just rerun it every hour, its going to grab the list, see the file is already downloaded and then waste the api call.

**Comment by jje1000** [comment]
Agreed- it would be great if it were possible to start in the middle of the likes. 

I've managed to export only around 1,500 of my roughly 35K likes before the program stops itself.

**Comment by BlisteringSyko** [comment]
I hit the Api limit at "Ask for liked posts 11025 - 11044... done"
After this, restarting the download i just get a failed to parse.

I emailed tumblr asking for a limit increase, and was denied. 
So unless this change can be made, im pretty much out of luck downloading the rest of my likes

**Comment by neuro-sys** [comment]
I will try to add the option to specify the start offset from the UI as soon as I get the opportunity. Sorry for the inconvenience.

**Comment by neuro-sys** [comment]
https://github.com/neuro-sys/tumblr-likes-downloader/issues/44
