### ISSUE TITLE
Downloading isn't working

### ISSUE THREAD

**Issue by LeoAndGit** [neuro-sys/tumblr-likes-downloader#45]
Win 10 Chrome
Just showing this and just open a tumblr webpage:

* Starting...
Initializing environment... done
Authorizing on tumblr...
Waiting until authorization flow is completed
Authorization URL: https://www.tumblr.com/oauth/authorize?oauth_token=
Please check your browser, and log into Tumblr as usual, then come back to this application

Thank you

**Comment by Dalton-West** [comment]
Do you get an auth token?

**Comment by LeoAndGit** [comment]
I find I made a stupid mistake. The OAuth key on the Tumblr web is hidden and just shows 'show'. I thought it is my key and filled 'show' into my programme. Now it works. 
I also notice that these is a 1000 requests per hour limitation, will the downloader download same things if I restart it?

**Comment by Dalton-West** [comment]
I was able to backup 12k likes in the hour. I did request a limit change as a just in case scenario.

**Comment by jeanpages** [comment]
Has your request been successful ? 
Thank you.

**Comment by BlisteringSyko** [comment]
I got denied my request to increase or remove the rate limit.
I was only able to download 11,044. 
The program will start over again from Zero so im going to loose over half my likes. (32k)

**Comment by neuro-sys** [comment]
I added a "Start Offset" option to specify a point to continue from with the latest release.
