### ISSUE TITLE
Failed to parse

### ISSUE THREAD

**Issue by kaoskorp** [neuro-sys/tumblr-likes-downloader#47]
Mac OS Chrome 

Starting...
Initializing environment...
done
Authorizing on tumblr...
Waiting until authorization flow is completed
Authorization URL: https://www.tumblr.com/oauth/authorize?oauth_token=XXX
Please check your browser, and log into Tumblr as usual, then come back to this application
XXX
Releasing now
Auth completed
Ask for liked posts 1 - 20... There was an error:
Failed to parse: response.liked_posts
Finished...

**Comment by neuro-sys** [comment]
I have added a Debug Mode to see the problem. But based on the logs, my guess is that the User Name (ex-Blog Name) you have put was incorrect, or someone else's, in which case you are not authorized to download the likes of some other user.
