### ISSUE TITLE
Having Trouble Getting Past "Please check your browser,"

### ISSUE THREAD

**Issue by zabeyman** [neuro-sys/tumblr-likes-downloader#48]
Bit of a novice when it comes to this but after triple checking that my keys were correct i cannot figure out why tumblr is opened, logged into and when i return to the application, nothing happens.
Would love to save my likes before the purge on the 17th any help would be appreciated.
full log below
* Starting...
Initializing environment... done
Authorizing on tumblr...
Waiting until authorization flow is completed
Authorization URL: https://www.tumblr.com/oauth/authorize?oauth_token=
Please check your browser, and log into Tumblr as usual, then come back to this application

**Comment by wakest** [comment]
having the same issue as above.

**Comment by neuro-sys** [comment]
> i cannot figure out why tumblr is opened, logged into and when i return to the application,

Before you return to the application, what message do you see on the browser after you login and "allow" permission?

As long as you do everything correctly, the only reason I can think of for this is some operating system firewall that will disallow port 8080 even locally. Although neither Windows, OSX or the Linux distros I've used does this. If that happens starting the application as Root/Administrator user could help.

**Comment by linkinliang** [comment]
same here

* Starting...
Initializing environment... 
Authorizing on tumblr... 
Waiting until authorization flow is completed
Authorization URL: https://www.tumblr.com/oauth/authorize?oauth_token=vCO12BXBqpYmFZcuLMwOTphjnhGMBwjlWBxiFwEXWHuOAVsPaF
Please check your browser, and log into Tumblr as usual, then come back to this application.
NITfkBKjYGQAQGo04tiJGP1k6WH971b0yWPnPHF3OisEJYY5F7 vCO12BXBqpYmFZcuLMwOTphjnhGMBwjlWBxiFwEXWHuOAVsPaF
Releasing now
Authorization complete
Ask for liked posts 1 - 50... [DEBUG] - http://api.tumblr.com/v2/blog/scott19910719.tumblr.com/likes?&api_key=LIdmBRtZ0x41JocATQ3lChXqzctrpGBs0S9TWBufaH9lJkRlC7&limit=50&offset=0
[DEBUG] - {
  "meta": {
    "msg": "OK",
    "status": 200
  },
  "response": {
    "liked_count": 1996,

* Finished...

and the browser shows 'Success! Now go check the app!', I use administrator user

**Comment by neuro-sys** [comment]
@linkinliang Please try the latest version.
