### ISSUE TITLE
Simple issues

### ISSUE THREAD

**Issue by reinepierre89** [neuro-sys/tumblr-likes-downloader#49]
Hi, having some issues to run the program : 
blocked at "Starting".

Using firefox.

How long is it supposed to run to go through "Starting" ?
Do i need to run QT and Go to use it or can it run itself through the exe file ?
![image](https://user-images.githubusercontent.com/45945395/50098892-c0472400-0214-11e9-98ac-a906e41d8217.png)

**Comment by neuro-sys** [comment]
Hello, I've added some error diagnostics and debug mode in the latest release. I am aware that sometimes it freezes, but the next time you click Cancel/Download, it should work. If that's not the case, with the latest release you'll see a more meaningful error message that can help me identify the problem.
