### ISSUE TITLE
REQUEST Pause/ Resume features

### ISSUE THREAD

**Issue by apmcodes** [neuro-sys/tumblr-likes-downloader#50]
Thank you very much for this wonderful tool. Really helpful.

Would be nice to have a pause/ resume feature. Currently, the download has to be Cancelled and then when started again, it goes through all already downloaded files and skips them.

**Comment by neuro-sys** [comment]
This https://github.com/neuro-sys/tumblr-likes-downloader/pull/52 helps with the issue, so closing this one.
