### ISSUE TITLE
Rate Limits

### ISSUE THREAD

**Issue by photologist** [neuro-sys/tumblr-likes-downloader#51]
**EDIT**: This is a duplicate of #44 -sorry 'bout that.

Unfortunately, the app is limiting my download to "1,000 requests per hour".  

But if I start the download process again, it doesn't pick up from where it left off, it goes back to the beginning, making its requests from the first like already downloaded. 

Is there a way to avoid that and pick up from where I left off, after the rate limit has expired?

Here's the exact message on the Tumblr OAuth page for reference:

_"**Rate Limits**
Newly registered consumers are rate limited to 1,000 requests per hour, and 5,000 requests per day. If your application requires more requests for either of these periods, please use the 'Request rate limit removal' link on an app above."_

**Comment by neuro-sys** [comment]
See: https://github.com/neuro-sys/tumblr-likes-downloader/issues/44
