### ISSUE TITLE
8080 Bind Error

### ISSUE THREAD

**Issue by factotumindustries** [neuro-sys/tumblr-likes-downloader#55]
Keep getting a "There was an error: listen tcp :8080: bind: An attempt was made to access a socket in a way forbidden by its access permissions."

Have tried several different machines (all W10) and running as Admin. This only has started happening recently. Can't see anything else using 8080...

Thoughts?

**Comment by neuro-sys** [comment]
@factotumindustries The error message comes from the library that I am using, which in turns gets the error from the OS. It is most probably what it says, i.e. an access issue, or something is already using 8080.

I am also on W10, and binding to 8080 doesn't typically require Admin privileges, so it shouldn't be needed. Maybe a new W10 updates has changed the things, although I haven't had any here.

I would use a tool similar to `netstat` to make sure there's nothing listening on 8080, and then try using something like `netcat` to bind to 8080 to see if it's allowed on the machine.

**Comment by neuro-sys** [comment]
It could be that there's a ghost process running (of this tumblr downloader application) in the background which occupies 8080. It should be visible with a tool like `netstat`.

> Have tried several different machines (all W10) and running as Admin.

This is somewhat suspicious though, unless something that triggers the ghost process is done on each machine, which leads to the same situation. I can't think of anything else right now.
